### ISSUE TITLE
Events API

### ISSUE THREAD

**Issue by xyzhang30** [xyzhang30/Schedule_Task_Management_App#7]
createEvent()
updateEvent
deleteEvent

**Comment by Vivianmxmf** [comment]
pip install Flask SQLAlchemy

from flask import Flask, request, jsonify
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'The_sql_file_we_use '
db = SQLAlchemy(app)


class Event(db.Model):
    event_id = db.Column(db.Integer, primary_key=True)
    account_id = db.Column(db.Integer, nullable=False)
    name = db.Column(db.String(100), nullable=False)
    location = db.Column(db.String(200), nullable=True)
    start_date = db.Column(db.DateTime, nullable=False)
    end_date = db.Column(db.DateTime, nullable=False)
    category = db.Column(db.String(100), nullable=True)

    def to_dict(self):
        return {
            'event_id': self.event_id, #integer
            'account_id': self.account_id, #integer
            'name': self.name, #string: the name of the event
            'location': self.location, #string
            'start_date': self.start_date.isoformat(),#Datetime
            'end_date': self.end_date.isoformat(),#Datetime
            'category': self.category #string:Academic,Entertaining 
        }
